---
- hosts: all

  tasks:
  - name: include token dict
    include_vars:
      file: "{{ playbook_dir }}/token-dict.yml"
 
  - name: find files for replace
    find:
      paths: /data
      patterns: "*.properties"
      recurse: yes
    register: find_properties

  - name: replace tokens
    replace:
      path:    "{{ item.0.path }}"
      regexp:  "{{ item.1.regexp }}"
      replace: "{{ item.1.replace }}"
      backup: yes
    with_nested:
      - "{{ find_properties.files }}"
      - "{{ tokens_to_replace }}"
