---
- hosts: all
  become: yes

  tasks:
  - debug: msg="ansible time micro {{ ansible_date_time.iso8601_micro }}"

  - name: install ntp
    yum:
      name: ntp
      state: present

  - name: start ntpd
    service:
      name: ntpd
      state: started
      enabled: yes

  - name: date millis
    command: date +%s%3N
